project:
  type: website
  output-dir: docs

website:
  title: "Jenny Brar - CPLN 5920 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: lab/lab_0/lab0_template.qmd
            text: "Lab 0: dplyr Basics"
          - href: lab/lab_1/lab1_template.qmd
            text: "Lab 1: Census Data Quality for Policy Decisions"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
